config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get "signup", to: "users#new"
  resources :users, except: [ :new ]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories, except: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 6, maximum: 100 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, uniqueness: true,
            length: { maximum: 25, minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { self.email = email.downcase if email }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [ :show, :edit, :update, :destroy ]
  before_action :require_user, except: [ :show, :index ]
  before_action :require_same_user, only: [ :edit, :update, :destroy ]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path, status: :see_other
  end


  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only modify the contents of your own article"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [ :index, :show ]

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully"
      redirect_to @category
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name was successfully updated"
      redirect_to @category
    else
      render "edit"
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can to perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "Incorrect email or password entered. Please try again."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :update, :destroy ]
  before_action :require_user, only: [ :edit, :update, :destroy ]
  before_action :require_same_user, only: [ :edit, :update, :destroy ]
  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was updated successfully"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Profile and all associated accounts were successfully deleted"
    redirect_to root_path, status: :see_other
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only modify your own profile"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_for(user, options = { size: "200x200" })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    robot_url = "https://robohash.org/#{hash}.png/bgset_any?size=#{size}"
    image_tag(robot_url, alt: user.username, class: "rounded-circle shadow mx-auto d-block")
  end
end

app/views/Shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/articles/_article.html.erb
<div class="container">
    <% @articles.each do |article| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header">
                        <%= link_to user_path(article.user), class: "text-decoration-none text-dark" do %>
                            By: <em><%= article.user.username %></em>
                        <% end %>
                        <% if article.categories.any? %>
                            <div><%= render article.categories %></div>
                        <% end %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to article.title, article_path(article), 
                            class: "text-success text-decoration-none" %></h5>
                        <p class="card-text"><%= truncate(article.description, length: 50) %></p>
                        <%= link_to "View", article_path(article), class: "btn btn-success" %>
                        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                            <%= link_to "Edit", edit_article_path(article), class: "btn btn-info" %>
                            <%= link_to "Delete", article_path(article), method: :delete, 
                                data: { turbo_method: :delete, turbo_confirm: "Are you sure you would like to delete this article?" }, 
                                class: "btn btn-danger" %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>
                            Created <%= time_ago_in_words(article.created_at) %> ago,
                            Last Updated <%= time_ago_in_words(article.updated_at) %> ago
                        </small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render "Shared/errors", obj: @article %>

            <%= form_with(model: @article, class: "shadow p-3 mb-3 mt-3 bg-white rounded", local: true, data: { turbo: false }) do |f| %>
                <%= f.text_field :title, class: "form-control shadow rounded mb-3", placeholder: "Title", autocomplete: :off %>
                <%= f.text_area :description, class: "form-control pb-5 shadow rounded mb-3", placeholder: "Description", autocomplete: :off %>
                <%= f.collection_select(:category_ids, Category.all, :id, :name,
                                    { prompt: "Select your category from the list below (can be empty) (hold cmd/ctrl to select multiple)" },
                                    { multiple: true, size: 5, class: "form-select shadow rounded mb-3" }) %>
                <%= f.submit class: "form-control btn btn-secondary btn-lg shadow rounded"%>
            <% end %>
        </div>

        <div class="mb-3">
            <%= link_to "[ Cancel and Return to Articles Listing ]", articles_path, class: "row justify-content-center text-decoration-none text-secondary mt-4" %>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles Listing</h1>

<%= render 'article' %>

<div class="text-center">
    <div class="d-inline-block">
        <div class="digg_pagination">
            <div class="page_info">
                <%= page_entries_info @article %>
            </div>
            <%= will_paginate @article, :container => false %>
        </div>
    </div>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4"><%= @article.title %></h1>

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header">
                    <%= link_to @article.user.username, @article.user, class: "text-decoration-none text-dark" %>
                    <%= link_to avatar_for(@article.user, size: "75x75"), @article.user, class: "me-4" %>
                    <% if @article.categories.any? %>
                        <div><%= render @article.categories %></div>
                    <% end %>
                </div>
                <div class="card-body">
                    <div class="card-text text-start mt-3"><%= simple_format(@article.description) %></div>
                    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
                        <%= link_to "Edit", edit_article_path(@article), class: "btn btn-info" %>
                        <%= link_to "Delete", article_path(@article), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you would like to delete this article?" }, class: "btn btn-danger" %>
                    <% end %>
                    <%= link_to "Return", articles_path, class: "btn btn-warning" %>
                </div>
                <div class="card-footer text-muted">
                    <small>
                        Created <%= time_ago_in_words(@article.created_at) %> ago,
                        Last Updated <%= time_ago_in_words(@article.updated_at) %> ago
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill text-bg-info text-decoration-none me-1" %>

app/views/categories/_form.html.erb
<%= form_with(model: @category, class: "shadow p-3 mb-3 mt-3 bg-white rounded", local: true, data: { turbo: false }) do |f| %>
    <%= f.text_field :name, class: "form-control shadow rounded mb-3", placeholder: "Category Name", autocomplete: :off %>
    <%= f.submit class: "form-control btn btn-secondary btn-lg shadow rounded" %>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit Category Name</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render "Shared/errors", obj: @category %>

            <%= render "form" %>
        </div>

        <div class="mb-3">
            <%= link_to "[ Cancel and Return to Category ]", category_path(@category), class: "row justify-content-center text-decoration-none text-secondary mt-4" %>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="container">
    <% @categories.each do |category| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to category.name, category_path(category), 
                            class: "text-success text-decoration-none" %></h5>
                        <p class="card-text mt-2"><%= pluralize(category.articles.count, "article") %></p>
                    </div>
                    <div class="card-footer text-muted">
                        <small>
                            Created <%= time_ago_in_words(category.created_at) %> ago,
                            Last Updated <%= time_ago_in_words(category.updated_at) %> ago
                        </small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

<div class="text-center">
    <div class="d-inline-block">
        <div class="digg_pagination">
            <div class="page_info">
                <%= page_entries_info @categories %>
            </div>
            <%= will_paginate @categories, :container => false %>
        </div>
    </div>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new Category</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render "Shared/errors", obj: @category %>

            <%= form_with(model: @category, class: "shadow p-3 mb-3 mt-3 bg-white rounded", local: true, data: { turbo: false }) do |f| %>
                <%= f.text_field :name, class: "form-control shadow rounded mb-3", placeholder: "Category Name", autocomplete: :off %>
                <%= f.submit class: "form-control btn btn-secondary btn-lg shadow rounded" %>
            <% end %>
        </div>

        <div class="mb-3">
            <%= link_to "[ Cancel and Return to Articles Listing ]", articles_path, class: "row justify-content-center text-decoration-none text-secondary mt-4" %>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
    <div class="text-center mt-4">
        <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-info" %>
    </div>
<% end %>

<h3 class="text-center mt-4">Articles: </h3>

<%= render 'articles/article' %>

<div class="text-center">
    <div class="d-inline-block">
        <div class="digg_pagination">
            <div class="page_info">
                <%= page_entries_info @articles %>
            </div>
            <%= will_paginate @articles, :container => false %>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer", class="footer bg-dark py-2">
    <div class="text-center text-white">
        <span class="text-white">
            <small><%= link_to "© Ethan Olivieri", "https://github.com/EthanOlivier", class: "text-white text-decoration-none" %></small>
        </span>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, message| %>
    <% if flash.notice.present? %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% else %>
        <% if flash.alert.present? %>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <%= message %>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to "Bloggers", users_path, class: "nav-link" %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Articles
                    </a>
                    <ul class="dropdown-menu">
                        <% if logged_in? %>
                            <li><%= link_to "Create New Article", new_article_path, class: "dropdown-item" %></li>
                        <% end %>
                        <li><%= link_to "View Articles", articles_path, class: "dropdown-item" %></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Categories
                    </a>
                    <ul class="dropdown-menu">
                        <% if logged_in? && current_user.admin? %>
                            <li><%= link_to "Create New Category", new_category_path, class: "dropdown-item" %></li>
                        <% end %>
                        <li><%= link_to "View Categories", categories_path, class: "dropdown-item" %></li>
                    </ul>
                </li>
                <% if logged_in? %>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= current_user.username %>'s <%= "Admin" if current_user.admin? %> Profile
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %></li>
                        <li><%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %></li>
                        <%= link_to "Delete profile", user_path(current_user), method: :delete, 
                            data: { turbo_method: :delete, turbo_confirm: "Are you sure you would like to delete your profile? This action is perminant and cannot be undone!" }, 
                            class: "dropdown-item text-danger" %>
                    </ul>
                </li>
                    <li class="nav-item">
                        <%= link_to "Log out", logout_path, class: "nav-link", data: {turbo_method: :delete} %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Log in", login_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign up", signup_path, class: "nav-link" %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Alpha Dash Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <%# Includes all stylesheet files in app/assets/stylesheets %> 
    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_include_tag "turbo", type: "module" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the About Page</h1>

<%= link_to "Articles Listing", articles_path %>
<%= link_to "Home Page", root_path %>

app/views/pages/home.html.erb
<div class="container">
    <div class="jumbotron" id="home-container">
        <div class="p-5 rounded-lg m-3 text-center text-white">
            <h1 class="display-4">Alpha Blog</h1>
            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
            <p><br>It uses utility classes for typography and spacing to space content out within the larger container.</p>
            <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
        </div>
    </div>
</div>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render "Shared/errors", obj: @user %>

            <%= form_with(model: @user, class: "shadow p-3 mb-3 mt-3 bg-white rounded", local: true, data: { turbo: false }) do |f| %>
                <%= f.text_field :username, class: "form-control shadow rounded mb-3", placeholder: "Enter a username", autocomplete: :off %>
                <%= f.email_field :email, class: "form-control shadow rounded mb-3", placeholder: "Enter your email address", autocomplete: :off %>
                <%= f.text_field :password, class: "form-control shadow rounded mb-3", placeholder: "Choose a password", autocomplete: :off %>
                <%= f.submit (@user.new_record? ? " Sign Up" : "Update Account"), class: "form-control btn btn-secondary btn-lg shadow rounded" %>
            <% end %>
        </div>

        <div class="mb-3">
            <%= link_to "[ Cancel and Return to Articles Listing ]", articles_path, class: "row justify-content-center text-decoration-none text-secondary mt-4" %>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="container">
    <% @users.each do |user| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header">
                        <%= link_to user.username, user, class: "text-decoration-none text-dark" %>
                    </div>
                    <%= link_to avatar_for(user, size: "200x200"), user %>
                    <p class="card-text mt-2"><%= pluralize(user.articles.count, "article") %></p>
                    <div class="card-body">
                        <%= link_to "View Profile", user, class: "btn btn-success" %>
                        <% if logged_in? && (current_user == user || current_user.admin?) %>
                            <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-info" %>
                            <%= link_to "Delete Profile", user, class: "btn btn-danger", method: :delete, 
                                data: { turbo_method: :delete, turbo_confirm: "Are you sure you would like to delete your profile? This action is perminant and cannot be undone!" } %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

<div class="text-center">
    <div class="d-inline-block">
        <div class="digg_pagination">
            <div class="page_info">
                <%= page_entries_info @user %>
            </div>
            <%= will_paginate @user, :container => false %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= avatar_for @user %>

<% if logged_in? && current_user == @user %>
    <div class="text-center mt-4">
        <%= link_to "Edit your profile", edit_user_path, class: "btn btn-info" %>
    </div>
<% end %>

<h3 class="text-center mt-4">Articles: </h3>

<%= render 'articles/article' %>

<div class="text-center">
    <div class="d-inline-block">
        <div class="digg_pagination">
            <div class="page_info">
                <%= page_entries_info @articles %>
            </div>
            <%= will_paginate @articles, :container => false %>
        </div>
    </div>
</div>